import CheckupPanel from './CheckupPanel';

export default function FinancesPage({
  profile,
  onProfileChange,
  isMobile,
  isTablet,
  cardStyle,
  cardSoftStyle,
  inputStyle,
  btnPrimary,
  btnNeutral,
  income,
  onIncomeChange,
  expenses,
  onExpenseChange,
  newCategory,
  onNewCategoryChange,
  onAddCategory,
  onDeleteCategory,
  catBusy,
  busy,
  month,
  token,
  userId,
  primaryGoal,
  isPro,
  onGoPlan,
  onResult,
  onAutoCheckup,
  totalExpenses,
}) {
  return (
    <CheckupPanel
      token={token}
      userId={userId}
      month={month}
      isMobile={isMobile}
      isTablet={isTablet}
      cardStyle={cardStyle}
      cardSoftStyle={cardSoftStyle}
      inputStyle={inputStyle}
      btnPrimary={btnPrimary}
      btnNeutral={btnNeutral}
      ledger={{ income, totalExpenses }}
      ledgerEditor={{
        profile,
        onProfileChange,
        month,
        income,
        onIncomeChange,
        expenses,
        onExpenseChange,
        newCategory,
        onNewCategoryChange,
        onAddCategory,
        onDeleteCategory,
        catBusy,
        busy,
      }}
      onResult={onResult}
      showForm
      showDetails={false}
      showHistory={false}
      profile={profile}
      primaryGoal={primaryGoal}
      isPro={isPro}
      onGoPlan={onGoPlan}
      autoSync
      onAutoCheckup={onAutoCheckup}
      dimensionCardLayout
    />
  );
}
